/*

 BKG_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : bkg_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bkg_map_h_INCLUDE
#define __bkg_map_h_INCLUDE

#define bkg_mapWidth 20
#define bkg_mapHeight 18
#define bkg_mapBank 0

extern const unsigned char bkg_map[];

#endif

/* End of BKG_MAP.H */
