//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_galaga_H
#define METASPRITE_galaga_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define galaga_TILE_H 16
#define galaga_WIDTH 16
#define galaga_HEIGHT 16
#define galaga_PIVOT_X 8
#define galaga_PIVOT_Y 8
#define galaga_PIVOT_W 16
#define galaga_PIVOT_H 16

BANKREF_EXTERN(galaga)

extern const uint16_t galaga_palettes[4];
extern const uint8_t galaga_tiles[64];

extern const metasprite_t* const galaga_metasprites[1];

#endif