//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_one_up_H
#define METASPRITE_one_up_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define one_up_TILE_H 16
#define one_up_WIDTH 16
#define one_up_HEIGHT 16
#define one_up_PIVOT_X 8
#define one_up_PIVOT_Y 8
#define one_up_PIVOT_W 16
#define one_up_PIVOT_H 16

BANKREF_EXTERN(one_up)

extern const uint16_t one_up_palettes[4];
extern const uint8_t one_up_tiles[32];

extern const metasprite_t* const one_up_metasprites[1];

#endif