//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tileset_H
#define METASPRITE_tileset_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tileset_TILE_H 16
#define tileset_WIDTH 16
#define tileset_HEIGHT 16
#define tileset_PIVOT_X 8
#define tileset_PIVOT_Y 8
#define tileset_PIVOT_W 16
#define tileset_PIVOT_H 16

BANKREF_EXTERN(tileset)

extern const uint16_t tileset_palettes[4];
extern const uint8_t tileset_tiles[64];

extern const metasprite_t* const tileset_metasprites[1];

#endif